# Generated by Django 5.0.3 on 2024-04-08 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_alter_client_registration_date_alter_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image of product'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateField(default=datetime.date(2024, 4, 8), verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 4, 8), verbose_name='Creation date'),
        ),
    ]
